# -*- coding: utf-8 -*-
"""cursobasicopy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/limav176/a340d04dd5706987399e528a1f37ee27/cursobasicopy.ipynb
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


listadir = os.listdir("/content/drive/MyDrive/py/Vendas")
# display(listadir)

tabela_total = pd.DataFrame()

# passo 2 importar bases



for arquivo in listadir:
    #print(arquivo)
    if "Vendas" in arquivo:
      tabela = pd.read_csv(f"/content/drive/MyDrive/py/Vendas/{arquivo}")
      tabela_total = pd.concat([tabela_total, tabela])

display(tabela_total)

# passo 4 - calcular produto mais vendido

# tabela.describe()

tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[['Quantidade Vendida', 'Preco Unitario']].sort_values(by='Quantidade Vendida', ascending=False)
display(tabela_produtos)

# passo 5 - calcular produto que mais vendeu em faturamento

tabela_total['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']
tabela_faturamento = tabela_total.groupby('Produto').sum()
tabela_faturamento = tabela_faturamento[['Faturamento', 'Quantidade Vendida']].sort_values(by='Faturamento', ascending=False)
display(tabela_faturamento)

# passo 6 - calcular a loja cidade que mais vendeu em faturamento

tabela_lojas = tabela_total.groupby("Loja", as_index = False).sum()
tabela_lojas = tabela_lojas[['Faturamento', 'Quantidade Vendida']].sort_values(by='Faturamento', ascending=False)
display(tabela_lojas)

import plotly.express as px
grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y='Faturamento')
grafico.show()